#

  

# Form implementation generated from reading ui file 'tblCores.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


#
#

#
#

#
#







from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(256, 192)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tblCores = QtWidgets.QTableWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblCores.sizePolicy().hasHeightForWidth())
        self.tblCores.setSizePolicy(sizePolicy)
        self.tblCores.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tblCores.setFont(font)
        self.tblCores.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.tblCores.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.tblCores.setLineWidth(0)
        self.tblCores.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.tblCores.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.tblCores.setAutoScroll(False)
        self.tblCores.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tblCores.setWordWrap(False)
        self.tblCores.setRowCount(1)
        self.tblCores.setColumnCount(5)
        self.tblCores.setObjectName("tblCores")
        self.tblCores.horizontalHeader().setVisible(True)
        self.tblCores.horizontalHeader().setCascadingSectionResizes(False)
        self.tblCores.horizontalHeader().setDefaultSectionSize(10)
        self.tblCores.horizontalHeader().setHighlightSections(False)
        self.tblCores.horizontalHeader().setMinimumSectionSize(5)
        self.tblCores.verticalHeader().setVisible(True)
        self.tblCores.verticalHeader().setDefaultSectionSize(22)
        self.verticalLayout_2.addWidget(self.tblCores)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
